### ISSUE TITLE
searching "furry" 504s and loads forever

### ISSUE THREAD

**Issue by advaith1** [discordextremelist/website#180]
![image](https://user-images.githubusercontent.com/11778454/98778643-843c7f80-23a7-11eb-914f-a25d9299bcdd.png)

**Comment by Cairo2k18** [comment]
tf

**Comment by IceeMC** [comment]
im hurt deeply

**Comment by advaith1** [comment]
also happens with "anime" and probably other queries

**Comment by TheAlienKnight** [comment]
So, the issue is that servers, aren't cached on startup, or on search. They are only cached on edit, submission, and autosync. It is why on the production site you can currently only find 1 page of server listings.

It took me a while to wrap my head around why results weren't showing up, and it seemed inconsistent depending on what selectors you chose. Bots, templates, and users, are cached. Servers are not, leading to a generally empty dataset that breaks the query and seems to cause an error. 

I'll see what I can come up with as far as a solution goes and make a PR in connection to this issue!

**Comment by TheAlienKnight** [comment]
I went ahead and added this to the current open PR since it's a small fix/change, I referenced the full, actual cause here https://github.com/TheAlienKnight/website/pull/10

**Comment by carolinaisslaying** [comment]
> I went ahead and added this to the current open PR since it's a small fix/change, I referenced the full, actual cause here [TheAlienKnight#10](https://github.com/TheAlienKnight/website/pull/10)

Is this resolved?

**Comment by carolinaisslaying** [comment]
@TheAlienKnight Is this resolved

**Comment by carolinaisslaying** [comment]
pretty sure this is resolved
